language : java
script : mvn install
jdk : oraclejdk8
cache:
  directories: $HOME/.m2
notifications:
    slack: intech-sudparis:Z3xKQEmZT2a9BFBqouokQ6J7
    on_success: change
    on_failure: always
branches :
    except: mvn-repo 
